stages:
    - build


jupiter-build:
  image: nixos/nix
  stage: build
  script:
    - ls -la
    - nix-build --version
    - nix flake show --extra-experimental-features flakes --extra-experimental-features nix-command
    - nixos-rebuild switch --flake .#jupiter
    - nix build --extra-experimental-features nix-command --extra-experimental-features flakes --flakes .#jupiter
    
