stages:
    - build


jupiter-build:
  image: nixos/nix
  stage: build
  script:
    - ls -la
    - nix-build --version
    - sudo nix build --extra-experimental-features nix-command --extra-experimental-features flakes
    
