stages:
    - build


jupiter-build:
  image: nixos/nix
  stage: build
  script:
    - ls -la
    - nix-build --version
    - cd machines
    - nix build --extra-experimental-features nix-command
    
